/**
 * R Plot Display Component
 * Displays publication-quality plots generated by R's metafor/meta packages
 */

import React, { useState } from 'react';
import {
  Box,
  Paper,
  Typography,
  CircularProgress,
  Alert,
  Button,
  ButtonGroup,
  Tooltip,
  IconButton,
  Menu,
  MenuItem,
  useTheme,
} from '@mui/material';
import {
  Download as DownloadIcon,
  Settings as SettingsIcon,
  Refresh as RefreshIcon,
} from '@mui/icons-material';

interface RPlotDisplayProps {
  plotType: string;
  imageBase64: string;
  title?: string;
  subtitle?: string;
  width?: number;
  height?: number;
  isLoading?: boolean;
  error?: string;
  onRefresh?: () => void;
  onSettingsClick?: () => void;
  testResults?: any;
}

const RPlotDisplay: React.FC<RPlotDisplayProps> = ({
  plotType,
  imageBase64,
  title,
  subtitle,
  width = 1000,
  height = 600,
  isLoading = false,
  error,
  onRefresh,
  onSettingsClick,
  testResults,
}) => {
  const theme = useTheme();
  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = `data:image/png;base64,${imageBase64}`;
    link.download = `${plotType}_${Date.now()}.png`;
    link.click();
  };

  const handleMenuOpen = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorEl(event.currentTarget);
  };

  const handleMenuClose = () => {
    setAnchorEl(null);
  };

  const handleDownloadFormat = (format: 'png' | 'svg' | 'pdf') => {
    // Would need backend support for different formats
    handleDownload();
    handleMenuClose();
  };

  return (
    <Paper sx={{ p: 3, height: '100%' }}>
      {/* Header */}
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
        <Box>
          {title && (
            <Typography variant="h6" fontWeight={600}>
              {title}
            </Typography>
          )}
          {subtitle && (
            <Typography variant="body2" color="text.secondary">
              {subtitle}
            </Typography>
          )}
        </Box>

        <Box sx={{ display: 'flex', gap: 1 }}>
          {onRefresh && (
            <Tooltip title="Refresh plot">
              <IconButton onClick={onRefresh} size="small">
                <RefreshIcon />
              </IconButton>
            </Tooltip>
          )}

          {onSettingsClick && (
            <Tooltip title="Plot settings">
              <IconButton onClick={onSettingsClick} size="small">
                <SettingsIcon />
              </IconButton>
            </Tooltip>
          )}

          <Tooltip title="Download">
            <IconButton onClick={handleMenuOpen} size="small">
              <DownloadIcon />
            </IconButton>
          </Tooltip>

          <Menu
            anchorEl={anchorEl}
            open={Boolean(anchorEl)}
            onClose={handleMenuClose}
          >
            <MenuItem onClick={() => handleDownloadFormat('png')}>
              Download as PNG
            </MenuItem>
            <MenuItem onClick={() => handleDownloadFormat('svg')}>
              Download as SVG
            </MenuItem>
            <MenuItem onClick={() => handleDownloadFormat('pdf')}>
              Download as PDF
            </MenuItem>
          </Menu>
        </Box>
      </Box>

      {/* Plot Image or Loading/Error State */}
      <Box
        sx={{
          position: 'relative',
          width: '100%',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          minHeight: 400,
        }}
      >
        {isLoading && (
          <Box sx={{ textAlign: 'center' }}>
            <CircularProgress />
            <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
              Generating publication-quality plot with R...
            </Typography>
          </Box>
        )}

        {error && !isLoading && (
          <Alert severity="error" sx={{ width: '100%' }}>
            <Typography variant="body2" fontWeight={600}>
              Failed to generate plot
            </Typography>
            <Typography variant="body2">{error}</Typography>
            {onRefresh && (
              <Button size="small" onClick={onRefresh} sx={{ mt: 1 }}>
                Try Again
              </Button>
            )}
          </Alert>
        )}

        {imageBase64 && !isLoading && !error && (
          <Box
            component="img"
            src={`data:image/png;base64,${imageBase64}`}
            alt={title || 'R Plot'}
            sx={{
              maxWidth: '100%',
              height: 'auto',
              border: `1px solid ${theme.palette.divider}`,
              borderRadius: 1,
            }}
          />
        )}
      </Box>

      {/* Test Results (if applicable) */}
      {testResults && !isLoading && (
        <Box sx={{ mt: 2, p: 2, backgroundColor: theme.palette.grey[50], borderRadius: 1 }}>
          <Typography variant="subtitle2" fontWeight={600} gutterBottom>
            Statistical Tests
          </Typography>

          {testResults.egger_test && (
            <Box sx={{ mb: 1 }}>
              <Typography variant="body2">
                <strong>Egger's Test:</strong> z = {testResults.egger_test.z.toFixed(3)},
                p = {testResults.egger_test.p_value.toFixed(4)}
                {testResults.egger_test.significant ? ' (significant)' : ' (not significant)'}
              </Typography>
            </Box>
          )}

          {testResults.trim_fill && testResults.trim_fill.n_imputed > 0 && (
            <Box>
              <Typography variant="body2">
                <strong>Trim & Fill:</strong> {testResults.trim_fill.n_imputed} studies imputed
                (adjusted effect: {testResults.trim_fill.adjusted_effect.toFixed(3)})
              </Typography>
            </Box>
          )}
        </Box>
      )}

      {/* Plot Info */}
      <Box sx={{ mt: 2, pt: 2, borderTop: `1px solid ${theme.palette.divider}` }}>
        <Typography variant="caption" color="text.secondary">
          Generated with R metafor/meta packages • Publication-ready quality
        </Typography>
      </Box>
    </Paper>
  );
};

export default RPlotDisplay;
